name: Angular Simple CI-CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --prod

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
        run: firebase deploy --token "$FIREBASE_TOKEN"
