name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install Firebase CLI
        run: npm install firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build -- --prod

      - name: Build & deploy
        run: npm run deploy
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
